Update 3_switch.yaml
Zverik/osmstreak pull request #61
Opened 2020-10-28 11:11 UTC by Strubbl

change title to match task description

2020-10-28 12:41 UTC, Zverik requested changes

2020-10-28 12:41 UTC, Zverik commented on tasks/3_switch.yaml
> +title: Make two Railway Switches
Please make it title case, "Two".

2020-11-01 20:18 UTC, Strubbl commented on tasks/3_switch.yaml
> +title: Make two Railway Switches
done

2020-11-02 07:43 UTC, merged

2020-11-02 07:43 UTC, Zverik commented
Thank you!